2024-09-04 11:51:35,759 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/nikitapomogalov/Urban/module_12/module_12_4/test_12_4.py", line 26, in test_run
    man = m.Runner(15)
          ^^^^^^^^^^^^
  File "/Users/nikitapomogalov/Urban/module_12/module_12_4/module_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-04 11:51:35,760 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/nikitapomogalov/Urban/module_12/module_12_4/test_12_4.py", line 15, in test_walk
    man = m.Runner('Skott', speed=-5)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitapomogalov/Urban/module_12/module_12_4/module_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
